/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframes;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mohit
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public ReturnBook() {
        initComponents();
    }
    //Get Book Details
    
   //Updating book detail
   public void updateBookDetails(){
       int bookId=Integer.parseInt(ISSUETbid.getText());
       try{
           Connection con =DBConnection.getConnection();
           String sql="update Book_Details set Quantity=Quantity+1 Where BookId=?";
           PreparedStatement pst=con.prepareStatement(sql);
           pst.setInt(1,bookId);
           int rowcount=pst.executeUpdate();
           if (rowcount>0){
               JOptionPane.showMessageDialog(this, "Book Count Updated");
           }else{
               JOptionPane.showMessageDialog(this, "Error");
           }
       }catch (Exception e){}
   }

//To fetch issue book details from database
   public void getIssueBookDetails(){
  
           int bid=Integer.parseInt(ISSUETbid.getText());
       int sid=Integer.parseInt(ISSUETsid.getText());
       try{
           Connection con=DBConnection.getConnection();
           String sql="Select * from Issue_Book_Details where book_id=? and student_id=? and status=?";
           PreparedStatement pst=con.prepareStatement(sql);
           pst.setInt(1, bid);
           pst.setInt(2, sid);
           pst.setString(3, "Pending");
           ResultSet rs=pst.executeQuery();
           if(rs.next())
           {
               ISBid1.setText(rs.getString("book_id"));
               ISBname1.setText(rs.getString("booK_name"));
               ISBstudentname1.setText(rs.getString("student_name"));
               ISBIssue.setText(rs.getString("issue_date"));
               ISBdue.setText(rs.getString("due_date"));
               Berror.setText("");
           }else{ 
               Berror.setText("No data found");
               ISBid1.setText(rs.getString(""));
               ISBname1.setText(rs.getString(""));
               ISBstudentname1.setText(rs.getString(""));
               ISBIssue.setText(rs.getString(""));
               ISBdue.setText(rs.getString(""));}
           
       }catch (Exception e){}
   }
   
   //Return book
   public boolean returnBook(){
       boolean isReturned=false;
        int bid=Integer.parseInt(ISSUETbid.getText());
       int sid=Integer.parseInt(ISSUETsid.getText());
       try{
           Connection con=DBConnection.getConnection();
           String sql="update Issue_Book_Details set status=? where student_id=? and book_id=? and status =?";
           PreparedStatement pst=con.prepareStatement(sql);
           pst.setString(1,"Returned");
           pst.setInt(2,sid);
           pst.setInt(3,bid);
           pst.setString(4,"Pending");
           
           int rowcount=pst.executeUpdate();
           if(rowcount>0){
           isReturned=true;
       }else
           {
               isReturned=false;
           }
       }catch (Exception e){}
       return isReturned;
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_Panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        IAquantity1 = new javax.swing.JLabel();
        ISBIssue = new app.bolivia.swing.JCTextField();
        ISBstudentname1 = new app.bolivia.swing.JCTextField();
        IAname1 = new javax.swing.JLabel();
        ISBname1 = new app.bolivia.swing.JCTextField();
        IBname1 = new javax.swing.JLabel();
        ISBid1 = new app.bolivia.swing.JCTextField();
        IBid1 = new javax.swing.JLabel();
        IAquantity2 = new javax.swing.JLabel();
        ISBdue = new app.bolivia.swing.JCTextField();
        Berror = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ISSUETsid = new app.bolivia.swing.JCTextField();
        ISSUETbid = new app.bolivia.swing.JCTextField();
        ISSUEbid = new javax.swing.JLabel();
        ISSUEsid1 = new javax.swing.JLabel();
        ISSUEadd = new necesario.RSMaterialButtonCircle();
        jButton2 = new javax.swing.JButton();
        ISSUEadd1 = new necesario.RSMaterialButtonCircle();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Main_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Main_Panel.setForeground(new java.awt.Color(255, 255, 255));
        Main_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Liberation Mono", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Book Details");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 300, 5));

        IAquantity1.setBackground(new java.awt.Color(255, 255, 255));
        IAquantity1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        IAquantity1.setForeground(new java.awt.Color(0, 0, 0));
        IAquantity1.setText("Issue Date");
        jPanel3.add(IAquantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, 30));

        ISBIssue.setBackground(new java.awt.Color(255, 102, 102));
        ISBIssue.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        ISBIssue.setForeground(new java.awt.Color(0, 0, 0));
        ISBIssue.setFont(new java.awt.Font("Liberation Sans", 0, 17)); // NOI18N
        ISBIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISBIssueActionPerformed(evt);
            }
        });
        jPanel3.add(ISBIssue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 380, -1));

        ISBstudentname1.setBackground(new java.awt.Color(255, 102, 102));
        ISBstudentname1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        ISBstudentname1.setForeground(new java.awt.Color(0, 0, 0));
        ISBstudentname1.setFont(new java.awt.Font("Liberation Sans", 0, 17)); // NOI18N
        ISBstudentname1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ISBstudentname1FocusLost(evt);
            }
        });
        ISBstudentname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISBstudentname1ActionPerformed(evt);
            }
        });
        jPanel3.add(ISBstudentname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 380, -1));

        IAname1.setBackground(new java.awt.Color(255, 255, 255));
        IAname1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        IAname1.setForeground(new java.awt.Color(0, 0, 0));
        IAname1.setText("Enter Student Name");
        jPanel3.add(IAname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, 30));

        ISBname1.setBackground(new java.awt.Color(255, 102, 102));
        ISBname1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        ISBname1.setForeground(new java.awt.Color(0, 0, 0));
        ISBname1.setFont(new java.awt.Font("Liberation Sans", 0, 17)); // NOI18N
        ISBname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISBname1ActionPerformed(evt);
            }
        });
        jPanel3.add(ISBname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 380, -1));

        IBname1.setBackground(new java.awt.Color(255, 255, 255));
        IBname1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        IBname1.setForeground(new java.awt.Color(0, 0, 0));
        IBname1.setText("Enter Book Name");
        jPanel3.add(IBname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 30));

        ISBid1.setBackground(new java.awt.Color(255, 102, 102));
        ISBid1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        ISBid1.setForeground(new java.awt.Color(0, 0, 0));
        ISBid1.setFont(new java.awt.Font("Liberation Sans", 0, 17)); // NOI18N
        ISBid1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ISBid1FocusLost(evt);
            }
        });
        ISBid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISBid1ActionPerformed(evt);
            }
        });
        jPanel3.add(ISBid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 380, -1));

        IBid1.setBackground(new java.awt.Color(255, 255, 255));
        IBid1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        IBid1.setForeground(new java.awt.Color(0, 0, 0));
        IBid1.setText("Enter Book ID");
        jPanel3.add(IBid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 30));

        IAquantity2.setBackground(new java.awt.Color(255, 255, 255));
        IAquantity2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        IAquantity2.setForeground(new java.awt.Color(0, 0, 0));
        IAquantity2.setText("Due Date");
        jPanel3.add(IAquantity2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, -1, 30));

        ISBdue.setBackground(new java.awt.Color(255, 102, 102));
        ISBdue.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        ISBdue.setForeground(new java.awt.Color(0, 0, 0));
        ISBdue.setFont(new java.awt.Font("Liberation Sans", 0, 17)); // NOI18N
        ISBdue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISBdueActionPerformed(evt);
            }
        });
        jPanel3.add(ISBdue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 380, -1));

        Berror.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        Berror.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(Berror, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 700, 260, 40));

        Main_Panel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 420, 810));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel5.setText("Return Book");
        Main_Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 90, 290, 80));

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        Main_Panel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 160, 380, 5));

        ISSUETsid.setBackground(new java.awt.Color(255, 102, 102));
        ISSUETsid.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        ISSUETsid.setForeground(new java.awt.Color(255, 255, 255));
        ISSUETsid.setFont(new java.awt.Font("Liberation Sans", 0, 17)); // NOI18N
        ISSUETsid.setPlaceholder("Enter Student ID");
        ISSUETsid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ISSUETsidFocusLost(evt);
            }
        });
        ISSUETsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISSUETsidActionPerformed(evt);
            }
        });
        Main_Panel.add(ISSUETsid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 380, 380, -1));

        ISSUETbid.setBackground(new java.awt.Color(255, 102, 102));
        ISSUETbid.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        ISSUETbid.setForeground(new java.awt.Color(255, 255, 255));
        ISSUETbid.setFont(new java.awt.Font("Liberation Sans", 0, 17)); // NOI18N
        ISSUETbid.setPlaceholder("Enter Book ID");
        ISSUETbid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ISSUETbidFocusLost(evt);
            }
        });
        ISSUETbid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISSUETbidActionPerformed(evt);
            }
        });
        Main_Panel.add(ISSUETbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 280, 380, -1));

        ISSUEbid.setBackground(new java.awt.Color(255, 255, 255));
        ISSUEbid.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        ISSUEbid.setForeground(new java.awt.Color(0, 0, 0));
        ISSUEbid.setText("Enter Book ID");
        Main_Panel.add(ISSUEbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 250, -1, 30));

        ISSUEsid1.setBackground(new java.awt.Color(255, 255, 255));
        ISSUEsid1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        ISSUEsid1.setForeground(new java.awt.Color(0, 0, 0));
        ISSUEsid1.setText("Enter Student ID");
        Main_Panel.add(ISSUEsid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 350, -1, 30));

        ISSUEadd.setBackground(new java.awt.Color(51, 51, 255));
        ISSUEadd.setText("FIND");
        ISSUEadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISSUEaddActionPerformed(evt);
            }
        });
        Main_Panel.add(ISSUEadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 520, 340, 80));

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Main_Panel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        ISSUEadd1.setBackground(new java.awt.Color(255, 51, 51));
        ISSUEadd1.setText("Return Book");
        ISSUEadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISSUEadd1ActionPerformed(evt);
            }
        });
        Main_Panel.add(ISSUEadd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 610, 340, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/library-2.png"))); // NOI18N
        Main_Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 90, 970, 610));

        getContentPane().add(Main_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 803));

        setSize(new java.awt.Dimension(1510, 833));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
HomePage hm=new HomePage();
hm.setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ISBIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISBIssueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISBIssueActionPerformed

    private void ISBstudentname1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ISBstudentname1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_ISBstudentname1FocusLost

    private void ISBstudentname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISBstudentname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISBstudentname1ActionPerformed

    private void ISBname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISBname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISBname1ActionPerformed

    private void ISBid1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ISBid1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_ISBid1FocusLost

    private void ISBid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISBid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISBid1ActionPerformed

    private void ISSUETsidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ISSUETsidFocusLost

// TODO add your handling code here:
    }//GEN-LAST:event_ISSUETsidFocusLost

    private void ISSUETsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISSUETsidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISSUETsidActionPerformed

    private void ISSUETbidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ISSUETbidFocusLost

    }//GEN-LAST:event_ISSUETbidFocusLost

    private void ISSUETbidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISSUETbidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISSUETbidActionPerformed

    private void ISSUEaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISSUEaddActionPerformed
getIssueBookDetails();
    }//GEN-LAST:event_ISSUEaddActionPerformed

    private void ISSUEadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISSUEadd1ActionPerformed
if(returnBook()==true){
    JOptionPane.showMessageDialog(this,"Return Success");
    updateBookDetails();
}else{// TODO add your handling code here:
    JOptionPane.showMessageDialog(this,"Return Failed");

}
    }//GEN-LAST:event_ISSUEadd1ActionPerformed

    private void ISBdueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISBdueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISBdueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Berror;
    private javax.swing.JLabel IAname1;
    private javax.swing.JLabel IAquantity1;
    private javax.swing.JLabel IAquantity2;
    private javax.swing.JLabel IBid1;
    private javax.swing.JLabel IBname1;
    private app.bolivia.swing.JCTextField ISBIssue;
    private app.bolivia.swing.JCTextField ISBdue;
    private app.bolivia.swing.JCTextField ISBid1;
    private app.bolivia.swing.JCTextField ISBname1;
    private app.bolivia.swing.JCTextField ISBstudentname1;
    private app.bolivia.swing.JCTextField ISSUETbid;
    private app.bolivia.swing.JCTextField ISSUETsid;
    private necesario.RSMaterialButtonCircle ISSUEadd;
    private necesario.RSMaterialButtonCircle ISSUEadd1;
    private javax.swing.JLabel ISSUEbid;
    private javax.swing.JLabel ISSUEsid1;
    private javax.swing.JPanel Main_Panel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
