/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframes;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/**
 *
 * @author mohit
 */
public class SignUpPage extends javax.swing.JFrame {

    /**
     * Creates new form SignUpPage
     */
    public SignUpPage() {
        initComponents();
    }
    //method to insert values into Users table
    public void insertSignupDetails(){
        String Uname=Username.getText();
        String password=Password.getText();
        String email=Email.getText();
        String contact=Contact.getText();
        
        try{
            Connection con = DBConnection.getConnection();
            String sql;
            sql = "insert into Users(name,email,contact,password) values (?,?,?,?)";
            PreparedStatement pst =con.prepareStatement(sql);
            
            pst.setString(1, Uname);
            pst.setString(4, password);
            pst.setString(2, email);
            pst.setString(3, contact);
            
            int updatedRowCount =pst.executeUpdate();
            if (updatedRowCount>0){
                JOptionPane.showMessageDialog(this,"Recorded Inserted Successfully");
                LoginPage login=new LoginPage();
                login.setVisible(true);
                this.dispose();
            }
                else
                JOptionPane.showMessageDialog(this, "Recorde Insertion Failed");
            

        }catch (Exception e){
            e.printStackTrace();
        }
    }
    //VALIDATION
    
       //validation of EMAIL and PASSWORD
    public boolean valEmail(){
        String email=Email.getText();
        String pattern="^[a-zA-Z0-9._]+\\.ies+@ipsacademy\\.org$";
        Pattern pat=Pattern.compile(pattern);
        Matcher Match=pat.matcher(email);
        return Match.matches();
    }
    public boolean valContact(){
        String contact=Contact.getText();
        String pattern="^[0-9]{10}$";
        Pattern pat=Pattern.compile(pattern);
        Matcher Match=pat.matcher(contact);
        return Match.matches();
        
    }
    
    //Validating everything
    
    public boolean ValidateSignup(){
        
        String Uname=Username.getText();
        String password=Password.getText();
        String email=Email.getText();
        String contact=Contact.getText();
       
        if (Uname.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter a valid username");
            return false;
        }
        
        if (password.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter a password");
            return false;
        }
        
        if (email.equals("") || valEmail()==false){
            JOptionPane.showMessageDialog(this, "Invalid email please enter a valid email address");
            return false;
        }
        if (contact.equals("") || valContact()==false){
            JOptionPane.showMessageDialog(this, "Invalid Contact please enter a valid contact");
            return false;
        }
        return true;
    }
    //dulpicasy of USERNAME
    public boolean checkDuplicateUSER(){
        String name=Username.getText();
        boolean isexist =false;
        try{
            Connection connect= DBConnection.getConnection();
            PreparedStatement pst =connect.prepareStatement("select *from Users where name=?");
            pst.setString(1,name);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                isexist=true;
            }
        }catch (SQLException e){
        }
        return isexist;
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Left_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Right_panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Username = new app.bolivia.swing.JCTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCTextField2 = new app.bolivia.swing.JCTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Password = new app.bolivia.swing.JCTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Email = new app.bolivia.swing.JCTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Contact = new app.bolivia.swing.JCTextField();
        jLabel18 = new javax.swing.JLabel();
        rSMaterialButtonCircle1 = new necesario.RSMaterialButtonCircle();
        rSMaterialButtonCircle2 = new necesario.RSMaterialButtonCircle();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Left_panel.setBackground(new java.awt.Color(255, 255, 255));
        Left_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel1.setText("Welcome To");
        Left_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel2.setText("IES Library ");
        Left_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel3.setText("IES Library ");
        Left_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/signup-library-icon.png"))); // NOI18N
        Left_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 990, 630));

        getContentPane().add(Left_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 830));

        Right_panel.setBackground(new java.awt.Color(255, 153, 153));
        Right_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Right_panel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 32, -1, -1));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel5.setText("Sign Up");
        Right_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        Right_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 60, 70));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel7.setText("Create New Account Here");
        Right_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, 30));

        Username.setBackground(new java.awt.Color(255, 153, 153));
        Username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        Username.setFont(new java.awt.Font("Liberation Sans", 0, 17)); // NOI18N
        Username.setPlaceholder("Enter Username");
        Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameFocusLost(evt);
            }
        });
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        Right_panel.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 380, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel8.setText("User Name");
        Right_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, 30));

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 32, -1, -1));

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel9.setText("Sign Up");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 60, 70));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel11.setText("Create New Account Here");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, 30));

        jCTextField2.setBackground(new java.awt.Color(255, 153, 153));
        jCTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField2.setFont(new java.awt.Font("Liberation Sans", 0, 17)); // NOI18N
        jCTextField2.setPlaceholder("Enter Username");
        jCTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField2ActionPerformed(evt);
            }
        });
        jPanel4.add(jCTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 380, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel12.setText("User Name");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, 30));

        Right_panel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 530, 828));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        Right_panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 60, 70));

        Password.setBackground(new java.awt.Color(255, 153, 153));
        Password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        Password.setFont(new java.awt.Font("Liberation Sans", 0, 17)); // NOI18N
        Password.setPlaceholder("Enter Password");
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        Right_panel.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 380, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel14.setText("Password");
        Right_panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, 30));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        Right_panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 60, 70));

        Email.setBackground(new java.awt.Color(255, 153, 153));
        Email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        Email.setFont(new java.awt.Font("Liberation Sans", 0, 17)); // NOI18N
        Email.setPlaceholder("<EnrollmentNumber>.ies@ipsacademy.org");
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        Right_panel.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 380, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel16.setText("Email");
        Right_panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, 30));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        Right_panel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 60, 70));

        Contact.setBackground(new java.awt.Color(255, 153, 153));
        Contact.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        Contact.setFont(new java.awt.Font("Liberation Sans", 0, 17)); // NOI18N
        Contact.setPlaceholder("Ph +91XXXXXXXXXX");
        Contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactActionPerformed(evt);
            }
        });
        Right_panel.add(Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 380, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel18.setText("Contact");
        Right_panel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 150, 30));

        rSMaterialButtonCircle1.setBackground(new java.awt.Color(255, 51, 51));
        rSMaterialButtonCircle1.setText("Log IN");
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });
        Right_panel.add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 710, 230, 80));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(255, 51, 51));
        rSMaterialButtonCircle2.setText("Sign Up");
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        Right_panel.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, 230, 80));

        jLabel19.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel19.setText("Sign Up");
        Right_panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        getContentPane().add(Right_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 530, 828));

        setSize(new java.awt.Dimension(1533, 858));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void jCTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField2ActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void ContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactActionPerformed

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
    if (ValidateSignup()==true){
        if(checkDuplicateUSER()==false){
            insertSignupDetails();  
            }else{
            JOptionPane.showMessageDialog(this, "Username Already Exist");
        }
            
    }
    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    private void UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusLost
        if (checkDuplicateUSER()==true){
            JOptionPane.showMessageDialog(this, "Username already exist");
        }
    }//GEN-LAST:event_UsernameFocusLost

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
LoginPage lp=new LoginPage();
lp.setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField Contact;
    private app.bolivia.swing.JCTextField Email;
    private javax.swing.JPanel Left_panel;
    private app.bolivia.swing.JCTextField Password;
    private javax.swing.JPanel Right_panel;
    private app.bolivia.swing.JCTextField Username;
    private app.bolivia.swing.JCTextField jCTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle2;
    // End of variables declaration//GEN-END:variables
}
