/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package jframes;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
    

/**
 *
 * @author mohit
 */


public class ViewRecord extends javax.swing.JFrame {

    /**
     * Creates new form ViewRecord
     */
    public ViewRecord() {
        initComponents();
        setDetails();
    }
    //set details to table
    public void setDetails(){
        try{
            Connection con =DBConnection.getConnection();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("Select * from Issue_Book_Details");
            DefaultTableModel model=new DefaultTableModel();
            while(rs.next()){
            String id=rs.getString("id");
            String bookname=rs.getString("booK_name");
            String Sname=rs.getString("student_name");
            String Idate=rs.getString("issue_date");
            String Ddate=rs.getString("due_date");
            String Status=rs.getString("status");

            
            Object[] obj={id,bookname,Sname,Idate,Ddate,Status};
            model = (DefaultTableModel) Stable.getModel();
            model.addRow(obj);
        }

            
        }catch (Exception e){
            
        }
    }
    //Method to clear the table
    public void clearTable(){
        DefaultTableModel model1=(DefaultTableModel) Stable.getModel();
        model1.setRowCount(0);
    }
    //to fetch the record from data base
    public void search(){
        DefaultTableModel model=new DefaultTableModel();
        Date Sdate=Startdate.getDatoFecha();
        Date Edate=Enddate.getDatoFecha();
        long S=Sdate.getTime();
        long E=Edate.getTime();
        java.sql.Date FDate=new java.sql.Date(S);
        java.sql.Date EDate=new java.sql.Date(E);
        try{
            Connection con=DBConnection.getConnection();
            String sql="Select * from Issue_Book_Details where issue_date between ? and ?";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setDate(1,FDate);
            pst.setDate(2,EDate);
            ResultSet rs=pst.executeQuery();
            if(rs.next()==false){
                JOptionPane.showMessageDialog(this,"No Records");
            }else{
            while(rs.next()){
                String id=rs.getString("id");
            String bookname=rs.getString("booK_name");
            String Sname=rs.getString("student_name");
            String Idate=rs.getString("issue_date");
            String Ddate=rs.getString("due_date");
            String Status=rs.getString("status");

            
            Object[] obj={id,bookname,Sname,Idate,Ddate,Status};
            model = (DefaultTableModel) Stable.getModel();
            model.addRow(obj);
            }
            }
        }catch (Exception e){}
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Startdate = new rojeru_san.componentes.RSDateChooser();
        ISSUEdate = new javax.swing.JLabel();
        Enddate = new rojeru_san.componentes.RSDateChooser();
        ISSUEdate1 = new javax.swing.JLabel();
        rSMaterialButtonCircle1 = new rojerusan.RSMaterialButtonCircle();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Stable = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Liberation Mono", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Records");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 300, 5));

        Startdate.setForeground(new java.awt.Color(255, 0, 0));
        Startdate.setColorBackground(new java.awt.Color(255, 0, 51));
        Startdate.setColorButtonHover(new java.awt.Color(255, 153, 153));
        Startdate.setColorDiaActual(new java.awt.Color(0, 0, 255));
        Startdate.setColorForeground(new java.awt.Color(255, 51, 102));
        Startdate.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        Startdate.setFuente(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        Startdate.setPlaceholder("Select Issue Date");
        jPanel1.add(Startdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 380, 50));

        ISSUEdate.setBackground(new java.awt.Color(255, 255, 255));
        ISSUEdate.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        ISSUEdate.setForeground(new java.awt.Color(0, 0, 0));
        ISSUEdate.setText("Issue Date");
        jPanel1.add(ISSUEdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 30));

        Enddate.setForeground(new java.awt.Color(255, 0, 0));
        Enddate.setColorBackground(new java.awt.Color(255, 0, 51));
        Enddate.setColorButtonHover(new java.awt.Color(255, 153, 153));
        Enddate.setColorDiaActual(new java.awt.Color(0, 0, 255));
        Enddate.setColorForeground(new java.awt.Color(255, 51, 102));
        Enddate.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        Enddate.setFuente(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        Enddate.setPlaceholder("Select Issue Date");
        jPanel1.add(Enddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 220, 380, 50));

        ISSUEdate1.setBackground(new java.awt.Color(255, 255, 255));
        ISSUEdate1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        ISSUEdate1.setForeground(new java.awt.Color(0, 0, 0));
        ISSUEdate1.setText("End Date");
        jPanel1.add(ISSUEdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 230, -1, 30));

        rSMaterialButtonCircle1.setBackground(new java.awt.Color(255, 0, 51));
        rSMaterialButtonCircle1.setText("Search");
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, -1, 70));

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 350));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setFont(new java.awt.Font("Liberation Mono", 0, 25)); // NOI18N

        Stable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Book Name", "Student Name", "Issue Date", "Due Date", "Status"
            }
        ));
        Stable.setColorBackgoundHead(new java.awt.Color(255, 0, 51));
        Stable.setRowHeight(44);
        jScrollPane1.setViewportView(Stable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 1310, 450));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 1480, 520));

        setSize(new java.awt.Dimension(1491, 905));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
        clearTable();
        search();        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
HomePage hm=new HomePage();
hm.setAlwaysOnTop(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        HomePage hm=new HomePage();
        hm.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.componentes.RSDateChooser Enddate;
    private javax.swing.JLabel ISSUEdate;
    private javax.swing.JLabel ISSUEdate1;
    private rojeru_san.complementos.RSTableMetro Stable;
    private rojeru_san.componentes.RSDateChooser Startdate;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle1;
    // End of variables declaration//GEN-END:variables
}
